### ISSUE TITLE
Support other lists

### ISSUE THREAD

**Issue by rayjlinden** [moov-io/watchman#108]
There are some other lists we need to monitor.  Would be great if this software handled them as well:

1) The UN Consolidated Sanctions List:
https://www.un.org/securitycouncil/content/un-sc-consolidated-list

2) The UK sanctions list:
https://www.gov.uk/government/publications/financial-sanctions-consolidated-list-of-targets/consolidated-list-of-targets

3) The EU sanctions list:
https://webgate.ec.europa.eu/europeaid/fsd/fsf#!/files

The third one is slightly annoying because you to create credentials to access the list.

**Comment by adamdecaf** [comment]
That sounds like a good idea. I don't know when I'd have time to work on this though.

**Comment by bherring** [comment]
I can't speak for the non-US lists, but I'm pretty sure the [Consolidated Sanctions](https://www.treasury.gov/resource-center/sanctions/SDN-List/Pages/consolidated.aspx) list is a very similar structure to the SDN list. Would that be possible to add? (is it already there and I just missed that section of the readme?)

**Comment by adamdecaf** [comment]
I think we would expand the fields included on the response of `GET /search` and query parameters. Right now I'm not planning to add other lists, but would help if anyone submits code to include other lists.

**Comment by wadearnold** [comment]
This project was originally intended to just provide and OFAC search for SDN. We have renamed the project to `watchman` to reflect the communities expand into other lists and 

UN Consolidated Sanctions List  #182
UK Office of Financial Sanctions Implementation (OFSI) #183
EU Consolidated list of sanctions #184

Unverified List (UVL) – Bureau of Industry and Security #185
Entity List – Bureau of Industry and Security #186
AECA Debarred List - State Department #188
Foreign Sanctions Evaders (FSE) - Treasury Department #189
Sectoral Sanctions Identifications List (SSI) - Treasury Department #190
Palestinian Legislative Council List (NS-PLC) - Treasury Department #191
CAPTA List #193
