### ISSUE TITLE
Add List: Nonproliferation Sanctions (ISN) - State Department

### ISSUE THREAD

**Issue by wadearnold** [moov-io/watchman#187]
[Nonproliferation Sanctions](https://www.state.gov/key-topics-bureau-of-international-security-and-nonproliferation/nonproliferation-sanctions/)

The ISN is part of the Consolidated Screening List (CSL)
[api.trade.gov/consolidated_screening_list](https://developer.trade.gov/consolidated-screening-list.html)

**Comment by ckelly-digicert** [comment]
@adamdecaf Possibly closed with fix #433
