### ISSUE TITLE
Add List: Foreign Sanctions Evaders (FSE) - Treasury Department

### ISSUE THREAD

**Issue by wadearnold** [moov-io/watchman#189]
[Foreign Sanctions Evaders (FSE) ](https://www.treasury.gov/resource-center/sanctions/SDN-List/Pages/fse_list.aspx)

OFAC publishes a list of foreign individuals and entities determined to have violated, attempted to violate, conspired to violate, or caused a violation of U.S. sanctions on Syria or Iran pursuant to Executive Order 13608. It also lists foreign persons who have facilitated deceptive transactions for or on behalf of persons subject to U.S. sanctions. Collectively, such individuals and companies are called “Foreign Sanctions Evaders” or “FSEs.” Transactions by U.S. persons or within the United States involving FSEs are prohibited.

The FSE List is not part of the Specially Designated Nationals (SDN) List. However, individuals and companies on the FSE List may also appear on the SDN List.

The FSE  is part of the Consolidated Screening List (CSL)
[api.trade.gov/consolidated_screening_list](https://developer.trade.gov/consolidated-screening-list.html)

**Comment by finservhp** [comment]
This would be useful. /Henrik
