### ISSUE TITLE
Add List: US Trade 8-Consolidated Screening List (CSL)

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/watchman#195]
Homepage: https://www.export.gov/article?id=Consolidated-Screening-List

This list seems to combine the information/names/entities from the below lists, a downloader and parser for this single list would be more efficient. 

https://github.com/moov-io/watchman/issues?q=is%3Aopen+is%3Aissue+label%3A%22Consolidated+Screening+List%22

The download requires an API key so requiring an env var like `US_CSL_API_KEY` should be required. If empty then the list is neither downloaded or indexed.

**Comment by adamdecaf** [comment]
Note: We should verify this consolidated list does combine the information from the 8 lists mentioned.

**Comment by atonks2** [comment]
Do we still need this issue? PR #197 added the Consolidated Screening List. 
The following sources can be easily extracted from it:
- Unverified List – Bureau of Industry and Security (Issue #185)
- Entity List – Bureau of Industry and Security (done, PR #199)
- Nonproliferation Sanctions (ISN) - State Department (Issue #187)
- Foreign Sanctions Evaders (FSE) - Treasury Department (Issue #189)
- Sectoral Sanctions Identifications List (SSI) - Treasury Department (done, PR #197)
- Palestinian Legislative Council List (PLC) - Treasury Department (Issue #191)

The CSL does contain the SDN and DPL, but those lists are available in a better format from the sources currently utilized.

**Comment by adamdecaf** [comment]
Not really. Thanks for the notice
