### ISSUE TITLE
search: ignore stopwords in entity names

### ISSUE THREAD

**Issue by atonks2** [moov-io/watchman#204]
The method implemented for removing stopwords from the SDN primary list (issue #176) seems to be working well. 

Stopwords should also be removed from the following sources:
- Sectoral Sanctions Identifications
  - Where type is NOT individual
- BIS Entity List

Additional lists to consider:
- SDN Alt Names
  - Doesn't indicate type (entity, individual, vessel, etc)
- SDN Addresses
  - I think it makes sense to remove stopwords, but it's open for debate

**Comment by adamdecaf** [comment]
SSI and BIS lists have their stopwords removed after that second PR. 

I don't think we should clean addresses, but maybe alt names. We should check the `.SDNType` when cleaning up alt names (to clean if it's not an individual).

**Comment by adamdecaf** [comment]
Stopwords are removed in the indexing of CSL (so SSI and BIS) records.
