### ISSUE TITLE
Potential collision and risk from indirect dependence "github.com/gotestyourself/gotestyourself"

### ISSUE THREAD

**Issue by KateGo520** [moov-io/watchman#284]
## Background
Repo `moov-io/watchman` used the old path to import `gotestyourself` indirectly.
This caused that `github.com/gotestyourself/gotestyourself` and `gotest.tools` coexist in this repo：
https://github.com/moov-io/watchman/blob/master/go.mod （Line 13 & 25）
```
github.com/gotestyourself/gotestyourself v2.2.0+incompatible // indirect
gotest.tools v2.2.0+incompatible // indirect 
```

That’s because the `gotestyourself` has already renamed it’s import path from "github.com/gotestyourself/gotestyourself" to "gotest.tools". When you use the old path "github.com/gotestyourself/gotestyourself" to import the `gotestyourself`, will reintroduces `gotestyourself` through the import statements "import gotest.tools" in the go source file of `gotestyourself`.

https://github.com/gotestyourself/gotest.tools/blob/v2.2.0/fs/example_test.go#L8 
```
package fs_test
import (
	…
	"gotest.tools/assert"
	"gotest.tools/assert/cmp"
	"gotest.tools/fs"
	"gotest.tools/golden"
)
```

"github.com/gotestyourself/gotestyourself" and "gotest.tools" are the same repos. This will work in isolation, bring about potential risks and problems. 

## Solution
Add replace statement in the go.mod file:
```
replace github.com/gotestyourself/gotestyourself => gotest.tools v2.3.0
```
Then clean the go.mod.

**Comment by KateGo520** [comment]
@adamdecaf  Could you help me review this issue? Thx :p

**Comment by adamdecaf** [comment]
Sure thing @KateGo520 I think we should update the gotest.tools dependency. I think we had this with another project.

**Comment by adamdecaf** [comment]
Since that dependency is transitive I ran `go get -u ./...` and the `go.sum` seems to be upgraded to their `/v3` release. Does that fix your issue?

I pushed a `upgrade-deps-2020-08-12` branch. Can you try that? 

If all looks good I can merge https://github.com/moov-io/watchman/pull/285

**Comment by KateGo520** [comment]
@adamdecaf  Thank you for your reply. I see the commit. I think it looks good. Thank you for your contribution!

**Comment by adamdecaf** [comment]
Merged. Can you let me know if Watchman isn't working for you after that update?

**Comment by KateGo520** [comment]
It seems good for me.@adamdecaf
