### ISSUE TITLE
Bug: When running re-search of watches and there is an issue reaching the web hook url, the server crashes

### ISSUE THREAD

**Issue by swhyte-rt** [moov-io/watchman#289]
Watchman Version: `current`

**What were you trying to do?**
Add a customer watch to server with a non existent web hook url and on next refresh of data, the  re-search of watches tries to hit that webhook url, the response is nil and kills the server.

`line 59: webhook.go`

**What did you expect to see?**

Server not crashing

**What did you see?**

Server crashing

**How can we reproduce the problem?**

see What I was doing.

**Comment by adamdecaf** [comment]
Did you add the webhook with the HTTP endpoints? I'm not sure how that was slipped through. We validate the webhook URL and reject in the case it's blank.

**Comment by swhyte-rt** [comment]
@adamdecaf I created the watch with the `/ofac/customers/watch?name=<watch name>` post endpoint.

In the body I had the following:
`{
    "authToken": "3411233213DD30000",
    "webhook": "https://localhost/3411233213DD30000"
}`

**Comment by adamdecaf** [comment]
@swhyte-rt Thanks. That's an oversight from us. I've fixed the calling code: https://github.com/moov-io/watchman/pull/290
