### ISSUE TITLE
Bug: When looping through the watches in spawnResearching, if a watch customer or company is does not have a SDN match, the body is not initialized and throws a panic in callWebhook which is should not call.

### ISSUE THREAD

**Issue by swhyte-rt** [moov-io/watchman#292]
Watchman Version: `v0.14.3`

**What were you trying to do?**
I added a customer watch at `/ofac/customers/watch?name=Taylor Green`, when in the spawnResearching method and looping through the for loop (line 49) it enters a switch statement where it looks at customerID, customerName, companyID and companyName. If the current watch record does not get to where the body is initialized (not found in SDNs), it continues down to callWebhook with a nil body object and causes a panic.

Actually will need to check if body is nil after a switch is complete.

**What did you expect to see?**
Move on to the next watch customer or company.

**What did you see?**
panic

**How can we reproduce the problem?**
see above.

**Comment by adamdecaf** [comment]
Was this different than https://github.com/moov-io/watchman/pull/291 ? I'm going to look at this issue.
