### ISSUE TITLE
Companies on the Entity List are not showing up

### ISSUE THREAD

**Issue by dhogan8** [moov-io/watchman#326]
Watchman Version: `0.16.0`

**What were you trying to do?**
Screen for company names found on the Consolidated Screening List: https://www.trade.gov/data-visualization/csl-search.

**What did you expect to see?**
We noticed that it appears not all of the Entity List company data shows up in the Watchman search results.

**What did you see?**
We did not see some of the companies in the Watchman search results that we found on https://www.trade.gov/data-visualization/csl-search.

**How can we reproduce the problem?**
By searching for some companies such as `Huawei` or `Hikvision`, you can see that they do not show up on the Watchman search results.

**Comment by adamdecaf** [comment]
Thanks for reporting these. We forgot to update the CSL parsing so https://github.com/moov-io/watchman/pull/327 fixes that.

I've also introduced a new config option to better handle exact matches and weight them over 100%. See https://github.com/moov-io/watchman/pull/328 for more details.

**Comment by adamdecaf** [comment]
This should be fixed in v0.17.0 - they'll appear under `bisEntities` from a search query (`GET /search?name=Huawei&sdnType=entity`)

https://github.com/moov-io/watchman/releases/tag/v0.17.0
