### ISSUE TITLE
Watch customer from `moov/customer`

### ISSUE THREAD

**Issue by mind-rot** [moov-io/watchman#331]
Watchman Version: `0.16`

General question:
Is there any plans to add support for `watchman` to make request to `moov/customer`?
Cuz currently i can watch by name, but it would be nice to tell `watchman` to check the guy from `customers`

**Comment by adamdecaf** [comment]
Nice MTG flair 🎉 !  We have implemented this the other way around. Customers has knowledge of calling Watchman and can store the results. We use this to automatically Reject Customer objects when the match percentage is too high.

See https://moov-io.github.io/customers/api/#get-/customers/-customerID-/ofac

**Comment by mind-rot** [comment]
Yeah, but the problem with this approach is that ofac list and customers are constantly updating. And i'm ending up with hitting `/customers/{customerID}/refresh/ofac` every once in a wile for every customer :(

**Comment by adamdecaf** [comment]
Yea. We need to include an async routine to refresh the OFAC results within Customers. It was removed in a refactor, but we should introduce it back into the service.
