### ISSUE TITLE
Watchman return more and higher match rate than OFAC sanctions search

### ISSUE THREAD

**Issue by praktochmalen** [moov-io/watchman#338]
Watchman Version: `0.17.1`

**What were you trying to do?**
search names on: https://sanctionssearch.ofac.treas.gov/ and https://oss.moov.io/watchman/ to compare the result

**What did you expect to see?**
We expect to see similar result and name match scores from both of them.

**What did you see?**
We noticed that Watchman search result shows more results with higher match scores.

**How can we reproduce the problem?**
search for name `emma daniels` on https://sanctionssearch.ofac.treas.gov/ and https://oss.moov.io/watchman/. you can see in Watchman result show `EMMA LLC` as 100% match rate and more of other results, while `ofac` only return 1 result with `emma` as match rate 87%.

**Comment by praktochmalen** [comment]
Is there any configurations I could use to show similar result like in the `ofac` site?

**Comment by adamdecaf** [comment]
@praktochmalen Thanks for the question. Watchman reports the top results so not everything included should be considered a positive match. Your application and specific requirements will give you a better estimate towards what match percentage works best for you. 

You could look at tweaking `EXACT_MATCH_FAVORITISM` and see other nobs to turn https://moov-io.github.io/watchman/usage-configuration/

**Comment by smehtaAA** [comment]
@adamdecaf Is there any recommended value for `EXACT_MATCH_FAVORITISM`.

**Comment by adamdecaf** [comment]
It depends on the language/region you're processing over. IIRC `AL` will create a lot of false positives with Arabic searches.
