### ISSUE TITLE
error messages when webhooks fail do not provide details

### ISSUE THREAD

**Issue by cushdan** [moov-io/watchman#344]
Watchman Version: `latest`

**What were you trying to do?**
receive webhooks on my local api with watchman running in docker (windows dev environment)

**What did you expect to see?**
error details. My assumption is that there is some more information on the issue with the http request that would make debugging simpler. If there are other debug flags that would help that would be enough but I didn't see anything configurable for that.

**What did you see?**
```
ts=2021-05-26T13:25:28.0110892Z caller=search_async.go:74 search="async: name watch 'Jane Smith' for company 0d55c2910a56d7566d75f234dc4431eb99f2ca6a found"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x98235e]

goroutine 47 [running]:
main.callWebhook(0xc003e582a0, 0x28, 0xc001b15830, 0xc003e582d0, 0x2d, 0xc0019aa520, 0xd, 0x0, 0x0, 0x0)
        /go/src/github.com/moov-io/watchman/cmd/server/webhook.go:62 +0x24e
main.(*searcher).spawnResearching(0xc0003f8380, 0xc5b900, 0xc0003f3050, 0xc615e0, 0xc002008120, 0xc61620, 0xc002008160, 0xc6e460, 0xc0020080e0, 0xc5bc80, ...)
        /go/src/github.com/moov-io/watchman/cmd/server/search_async.go:90 +0x2ce
created by main.main
        /go/src/github.com/moov-io/watchman/cmd/server/main.go:184 +0x119a
```

**How can we reproduce the problem?**
add a watch with a webhook that will not succeed. This same error occurred for a few scenarios

1. ssl validation issues
2. timeout
3. connection failure (api not running)

**Comment by adamdecaf** [comment]
@cushdan can you help me figure out which version of Watchman is being used? I'm seeing that exact line being a nil check, which wouldn't panic like your stack trace. 

https://github.com/moov-io/watchman/blob/6d4b3332428916c5c2f9916025a2a6977df6c38e/cmd/server/webhook.go#L60-L63

**Comment by adamdecaf** [comment]
I did wrap the response body `Close()` in a nil check, which could be a panic. See https://github.com/moov-io/watchman/commit/2403c40839d981016c070e78ea36ca2b1d104b22

**Comment by cushdan** [comment]
I pulled the latest recently. This is what it shows up as in docker

moov/watchman | latest | 52c0d4cea379 | about 1 year ago | 161.44 MB

```
latest: Pulling from moov/watchman
Digest: sha256:1fe03d96f4a64b08c02109bcd0e4e8bde1a2b8898534f6880e95e27fc4f5a4fc
Status: Image is up to date for moov/watchman:latest
docker.io/moov/watchman:latest
```

sounds like you might have fixed it though? I can try and recreate it when it's available

**Comment by adamdecaf** [comment]
https://hub.docker.com/layers/moov/watchman/latest/images/sha256-1fe03d96f4a64b08c02109bcd0e4e8bde1a2b8898534f6880e95e27fc4f5a4fc?context=repo 

That is the most recent release, so I'm surprised it panic'd there. Perhaps that stacktrace was triggered by another error? 

I can make a bugfix release with that nil check today.

**Comment by adamdecaf** [comment]
v0.18.2 is out with that bug fix -- https://github.com/moov-io/watchman/releases/tag/v0.18.2
