### ISSUE TITLE
api: User ID is required when updating a company or customer status

### ISSUE THREAD

**Issue by nlakritz** [moov-io/watchman#346]
Watchman Version: `v0.18.1`

**What were you trying to do?**
Update an SDN customer or company status using `PUT` `/ofac/companies/{companyID}` or `/ofac/customers/{customerID}` without specifying a `X-User-ID` in the request header.

**What did you expect to see?**
No response body, and an updated status for the given entity.

**What did you see?**
A `{"error":"no userID (X-User-Id header) found"}` response and no change in the entity's status.

**How can we reproduce the problem?**
`curl -X PUT -d '{"status": "exception", "notes":"random note"}' localhost:8084/ofac/companies/2831`

**Note**
I'm not sure if this is by design, and the documentation is just outdated.

**Comment by adamdecaf** [comment]
This is by design so that a bit of an audit trail can be collected. However I see those endpoints requiring x-user-id a bit too often.

**Comment by adamdecaf** [comment]
@nlakritz I created https://github.com/moov-io/watchman/pull/347 which removes the x-user-id usages outside of this bug. That status update still requires it (which is something we could look at removing).

**Comment by adamdecaf** [comment]
I'm open to making this optional, but would like more community input.

**Comment by adamdecaf** [comment]
Removed in v0.26.0
