### ISSUE TITLE
webhooks for watches with no matches are not called

### ISSUE THREAD

**Issue by cushdan** [moov-io/watchman#349]
Watchman Version: `0.18.2`

**What were you trying to do?**
Receive results from watches each time a watch was run. We would like responses even if there is not a hit so that we can log and provide evidence that ofac is run regularly. Could this behavior be configurable?

**What did you expect to see?**
webhook called with results after ofac data updated and searches re-run

**What did you see?**
on no matches it is logged but the webhook is [not called](https://github.com/moov-io/watchman/blob/d663ac8b5d2f95d2205a42ad1f28ca8cca5c2ceb/cmd/server/search_async.go#L56)
`search="async: no body rendered for watchID=83f0dc47c32d5f8168eee5a9f5acd5fe9c151095 - skipping`

**How can we reproduce the problem?**
create a watch for an individual that has no sdn hits

**Comment by adamdecaf** [comment]
Ah I see what you're doing here. Are your watches over specific ID's that aren't in the OFAC list anymore? If you were performing name watches I'd think there'd be _some_ result returned.

**Comment by cushdan** [comment]
these were name watches for a customer. I recreated the empty SDN results in the [ui](https://oss.moov.io/watchman/?name=dan%20cushman&limit=10&sdnType=individual) with my name ("Dan Cushman") and filtering on `individual`.

**Comment by cushdan** [comment]
I think the root cause of why no SDN is being returned is that for the name watches the [async search](https://github.com/moov-io/watchman/blob/9c65e47b23a4bc4ee008bd2bf5667e1f9c5e22d1/cmd/server/search_async.go#L83):
1. searches SDNs with the customer name
2. gets the top 5 results
3. then filters those 5 results by the `sdnType` (in this case `individual`)

For the name I was using, the first SDN of type individual is returned as the 17th results (based on ordered match percentage) with a percentage of `76.6%`.

I noticed similar behavior with the regular search api. I was trying to get the top result for a company so had set parameters to `sdnType=entity&limit=1` but then I received no results since the top result was a `vessel` and not an `entity`.

This does seem like a bug that could hide results from being returned in both search scenarios

**Comment by adamdecaf** [comment]
Oh strange.. We might have that filtering occurring too late in the search code then.

**Comment by adamdecaf** [comment]
I created https://github.com/moov-io/watchman/pull/350 to try and address this. It changes the filtering to occur prior to accumulation (inside of `TopSDNs(..)`). Could you try it out and look over the code?

**Comment by adamdecaf** [comment]
@cushdan I've fixed this with #350 and am getting results now. 

![Screen Shot 2021-06-09 at 5 04 19 PM](https://user-images.githubusercontent.com/120951/121444646-c2e9e680-c944-11eb-96f0-814ac30283fc.png)

**Comment by cushdan** [comment]
awesome, sorry I didn't get a chance to test it yet. I'm not very familiar with `go` but from your description of the approach and what I saw it sounds like the right solution. Really appreciate it!

**Comment by adamdecaf** [comment]
Awesome. I'll release the fix in v0.19.0. Building now https://github.com/moov-io/watchman/actions/runs/925658477
