### ISSUE TITLE
Cannot run docker imager

### ISSUE THREAD

**Issue by sinh117801** [moov-io/watchman#380]
Watchman Version: `v0.21.3 on Docker moov/watchman:latest`

**What were you trying to do?**
I try to run watchman on my local machine via docker image.

**What did you expect to see?**

**What did you see?**
I got this error like in the image below.

<img width="1440" alt="Screen Shot 2021-11-16 at 3 44 37 PM" src="https://user-images.githubusercontent.com/43696715/141953529-a28e1aee-c0d1-4e66-92b7-2a87a32d46fb.png">

**How can we reproduce the problem?**
Run this command:

```
docker pull moov/watchman:latest
docker run -p 8084:8084 -p 9094:9094 moov/watchman:latest
```

**Comment by adamdecaf** [comment]
Sorry about that @sinh117801 the `:latest` tag wasn't properly pushed before. It works now and `moov/watchman:v0.21.3` also works.

**Comment by sinh117801** [comment]
@adamdecaf - Thanks
