### ISSUE TITLE
CSL: Search over Unverified List (UVL) 

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/watchman#403]
Watchman Version: `v0.21.5`

**What were you trying to do?**
I'm trying to retrieve results from the Unverified List that appear in the Consolidated Screening List. 

**What did you see?**
No results are returned.

**Comment by adamdecaf** [comment]
We should be able to pull these out by filtering on `Unverified List (UVL) - Bureau of Industry and Security` from the `.csv` file. [Example CSV file](https://github.com/moov-io/watchman/blob/master/test/testdata/csl.csv)

The filtering can occur here: https://github.com/moov-io/watchman/blob/master/pkg/csl/reader.go#L46 

The `csl` package would need to define a struct for the appropriate fields.

We will need to precompute the data: https://github.com/moov-io/watchman/blob/master/cmd/server/search.go#L765

Then combine these results into the TopN functions. https://github.com/moov-io/watchman/blob/master/cmd/server/search.go#L485

**Comment by adamdecaf** [comment]
The precomputation was cleaned up fyi
https://github.com/moov-io/watchman/blob/master/cmd/server/search_us_csl.go#L13

**Comment by ckelly-digicert** [comment]
Proposed changes are in fix #432.

**Comment by ckelly-digicert** [comment]
Fix #432 has been merged. I believe this issue can now be closed. 🎉
