### ISSUE TITLE
Add support for OFSI Consolidated List Search 

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/watchman#424]
This is a meta-issue for including this list into search results. There are several lists to include, so we should plan how to add these.

Docs: https://sanctionssearchapp.ofsi.hmtreasury.gov.uk/

Questions:
- New endpoint?
- Do we need any additional parsing for UK specific formats?
- **How can we download this data?** API requests for each search will be slow.

**Comment by bryanuhri** [comment]
This may be a duplicate of https://github.com/moov-io/watchman/issues/183.
