### ISSUE TITLE
Proposal: Improve Jaro-Winkler 

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/watchman#469]
From the following paper implement the improvements under a new algorithm for testing. 

> On the Efficient Execution of Bounded Jaro-Winkler Distances

Source: https://www.semantic-web-journal.net/system/files/swj1128.pdf

[On the Efficient Execution of Bounded Jaro-Winkler Distances.pdf](https://github.com/moov-io/watchman/files/10320758/On.the.Efficient.Execution.of.Bounded.Jaro-Winkler.Distances.pdf)

**Comment by tstkenny** [comment]
Is there any progress please?  The current searching mechanism returns too many false matches..

**Comment by adamdecaf** [comment]
Improvements released in v0.25.0 - if anyone runs into more issues please file an issue or comment here.
