### ISSUE TITLE
proposal: Don’t log search queries

### ISSUE THREAD

**Issue by baldurh** [moov-io/watchman#488]
Currently, this is logging all search queries which means sensitive customer information (PII) is being stored in logs.

There are some options:
- Don’t log search queries at all
- Configure logging of search queries using an env variable (on/off)
- Change the logging of search queries to `trace` so that the current `LOG_LEVEL` configuration prevents them from getting logged.

**Comment by adamdecaf** [comment]
Thanks for the call out. Not sure how that snuck through all these years.
