### ISSUE TITLE
Downloaded sanction list text/csv files are not deleted after they are not needed any more

### ISSUE THREAD

**Issue by m29h** [moov-io/watchman#536]
The downloader package [here](https://github.com/moov-io/watchman/blob/master/pkg%2Fdownload%2Fclient.go#L70) creates a new temporary directory (with random directory name) every time the sanction lists are refreshed. (Standard every twelve hours) 

The file content is parsed immediately after the download and then abandoned.

This fills up the `/tmp` folder over time. A docker container running 24/7 will waste a couple of GB of physical storage every week of running. It is not much but noticeable over time.

Is there a reason why the temp files are not deleted immediately after they are not used any more. One could even use a suitable in memory buffer instead of a physical temporary file to avoid this in the first place!

**Comment by adamdecaf** [comment]
No real reason why it's not deleted yet. We can remove it after parsing.
