### ISSUE TITLE
Regression in v0.28.1 (nil pointer dereference)

### ISSUE THREAD

**Issue by m29h** [moov-io/watchman#538]
Watchman Version: v0.28.1

**What were you trying to do?**

`docker run moov/watchman:v0.28.1`

**What did you expect to see?**

working container

**What did you see?**

```
ts=2024-03-12T20:32:32Z msg="Starting watchman server version v0.28.1" level=info
ts=2024-03-12T20:32:32Z msg="looking for  database provider" level=info
ts=2024-03-12T20:32:32Z msg="sqlite version 3.44.0" database=sqlite level=info
ts=2024-03-12T20:32:32Z msg="allowing only 1024 workers for search" level=info
ts=2024-03-12T20:32:32Z msg="Starting refresh of data" component=pipeline level=info
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x94ef55]

goroutine 1 [running]:
main.(*searcher).refreshData(0xc0001e7d40, {0x0, 0x0})
	/go/src/github.com/moov-io/watchman/cmd/server/download.go:277 +0x4b5
main.main()
	/go/src/github.com/moov-io/watchman/cmd/server/main.go:160 +0xf34

```

**How can we reproduce the problem?**

compare the output of  `docker run moov/watchman:v0.28.1`
`docker run moov/watchman:v0.28.0` (which is working version)

note: docker is not related to the issue, it is just a quick way to reproduce.

I have understood the problem already (quick fix) and will post a PR immediately

It is however completely strange to me why all the CI checks have passed, and the released version does not run any more...

**Comment by adamdecaf** [comment]
Fixed in https://github.com/moov-io/watchman/pull/539
