### ISSUE TITLE
Unable to start service during government website outages  

### ISSUE THREAD

**Issue by haleyhartin7** [moov-io/watchman#570]
Watchman Version: `v0.28.2`

**What were you trying to do?**

The container start up fails when the [EU website](https://webgate.ec.europa.eu) is having outages. We see the following errors on container start up:
`ts=2024-10-06T05:36:35Z msg="ERROR: failed to download/parse initial data: EUCSL: EU CSL file is empty or missing\n" errored=true level=info`

**What did you expect to see?**
With our previous version, v0.27.0, when these outages happened, the container was still able to start successfully, and the list would be set to an empty list. 

**What did you see?**
Container start up failing with the error: 
`ts=2024-10-06T05:36:35Z msg="ERROR: failed to download/parse initial data: EUCSL: EU CSL file is empty or missing\n" errored=true level=info`

**How can we reproduce the problem?**
Spin up the container when there is an outage on the eu website, or by providing an empty string as the EU_CSL_DOWNLOAD_URL.

**Comment by adamdecaf** [comment]
This is somewhat intentional when watchman is expected to load the list, so that a failure doesn't silently fail. 

I don't see a `WITH_EU_SANCTIONS_LIST` boolean option to skip download. I'll add that to match `WITH_UK_SANCTIONS_LIST`.

**Comment by adamdecaf** [comment]
Added in https://github.com/moov-io/watchman/commit/04b0db5aea39309b7d5c1c31a3e2dcdf4e7c7fdc

**Comment by adamdecaf** [comment]
Included in https://github.com/moov-io/watchman/releases/tag/v0.29.1
